language: cpp
compiler: gcc
dist: trusty

before_install:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install -qq qt5-default qttools5-dev-tools qt5-qmake
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - qmake wakeonlan.pro
  - make
